name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use API Key
      run: echo "Using the API Key"
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - name: Another Step
      run: |
        echo "Your API key is $API_KEY"
      env:
        API_KEY: ${{ secrets.API_KEY }}
